---
title: "About"
output:
  distill::distill_article:
    includes: 
      in_header: _header.html
    self_contained: false
---

<style>

d-title h1 {
  /* font-family: 'Open Sans Condensed', Roboto, Helvetica, Arial, sans; */
  font-style: normal;
  font-variant: small-caps;
  font-weight: 400;
  font-size: 300%;
  color: #040404;
  margin-top: 2.1rem;
  margin-bottom: 1.2rem;
  padding-bottom: 1rem;
}

.headline p {
  font-family: 'Open Sans Condensed', Roboto, Helvetica, Arial, sans;
  font-variant: small-caps;
}
</style>

<div class="headline">
A mathematics graduate diving in data and computer science. Featuring new technologies and be able to pick up and apply them in a short time. From t-test to deep learning; from infrastructure to micro-services. 
</div>

I graduated from the University of Hong Kong in Mathematics. Soon after graduation, I joined the fantastic team involving cloud infrastructure building and data analytics for the first online counselling platform in Hong Kong, [OpenUp](https://www.openup.hk/). Experienced in using Chef Infra to set up virtual machines on Azure, networking routing, ports configuration to setting up MongoDB, analytics platform like Jupyter Lab and RStudio Server, visualisation platform like Shiny Dashboard. Also performed statistical analysis on the data. Applying a zero-truncated one-inflated negative binomial regression on count to identify repeated users, helping service team in manpower allocation. 

Moved to the UK in [Tailify Software](https://www.tailify.com/). Handled ten of millions rows of data with PySpark. Applied naive bayes and softmax regression in Keras to build machine learning models to predict the demographics of audiences. Deployed the models via FastAPI. Applying mathematical knowledge in real word business cases - enhancing existing cosine similarity matching model by adding a correlation matrix in the middle: 

$$\text{similarity} = \mathbf{x}^T K \mathbf{y} = \mathbf{x}^T K^{1/2} K^{1/2} \mathbf{y} = (K^{1/2} \mathbf{x})^T (K^{1/2} \mathbf{y}),$$
where $K$ is the correlation matrix of the features in both $\mathbf{x}$ and $\mathbf{y}$ (note that $K^{1/2}$ is the unique symmetric matrix such that $K^{1/2} K^{1/2} = K$ because $K$ is positive definite). This modified matching model no longer assume the features are completely independent to each other and has matched 10-15% more top performers (in terms of conversion rate, depends on brand). Also wired Google Drive, Google Sheets, ElasticSearch, PostgreSQL, Slack together to build micro-services for the client team to lookup the above matching score. Also exposed to dashboard building in Grafana and Google Looker. 

<br><br>

<div style='text-align: center;  color: #3a3a9f'>
<span itemprop="name" style="font-variant: small-caps; color: #3a3a9f; font-size: 150%">Wilson Yip</span>

<a style='color: #3a3a9f' href="mailto:wilsonyip@elitemail.org" title="Email me" class = 'social-icon'><span class="fa-stack fa-lg" aria-hidden="true">
  <i class="fa fa-circle fa-stack-2x"></i>
  <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
</span>
<span class="sr-only">Email me</span>
</a>
<a style='color: #3a3a9f'href="https://github.com/wilsonkkyip" title="GitHub" class = 'social-icon'>
  <span class="fa-stack fa-lg" aria-hidden="true">
    <i class="fa fa-circle fa-stack-2x"></i>
    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
  </span>
  <span class="sr-only">GitHub</span>
</a>
<a style='color: #3a3a9f' href="https://www.linkedin.com/in/wilsonkkyip/" title="LinkedIn" class = 'social-icon'><span class="fa-stack fa-lg" aria-hidden="true">
  <i class="fa fa-circle fa-stack-2x"></i>
  <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
</span>
<span class="sr-only">LinkedIn</span>
</a>

</div>

