name: create-linkedin-post

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Chekcout
        uses: actions/checkout@v3
      
      - name: Install python dependencies
        run: pip install srsly pyyaml
      
      - name: Create Linkedin Post
        run: python ./tools/cd/linkedin_post.py